# Site settings
title: LearnTo
email: LearnTo@Charged.City
url: http://learn-to.co.uk/
description: "SOME TEXT HERE SOME TEXT HERE SOME TEXT HERE SOME TEXT HERE SOME TEXT HERE SOME TEXT HERE SOME TEXT HERE "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: LearnTo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/LearnTo_Belfast

# Build settings
markdown: kramdown
permalink: pretty
